# ROSALIND PROBLEMS

# Bioinformatics stronghold: https://rosalind.info/problems/list-view/

# Problem 3: Reverse complement -----
# https://rosalind.info/problems/revc/

# We are given a DNA string
# We have to return the reverse complement.

# Define the nucleotide pairs
DNANucPairs = {"A":"T", "C":"G", "G":"C", "T":"A"}

# Read the file into a string
myDNA="TTTGCCACGGAGCTGTACATGCGATAGCTAACGCTGCGCAATGTGCCCCGATAGGTTTGCCCCACATGACAGCTGATACTCGTCCTCGTACCCATCGGCCCAAACCTGGCCAGACTCGCCTAACAGGCGTGAGTCTAATCGAACCATGTAGGTAGGGTTAATAGACGCTTACAGGGTGCGAGAGAGTAAAAAGGGACATTGCGCCGTGTACTGCATCATCAGGGTCGAGTCTTCCGCTACTAACCATATCCTAGTCGGACAGGTATTGGCTGCGGTATATTTCGGCGTTGCGGCAAAAGCGACTTGAAACAGCTAGCTTCGAGTCTCATCTAGGGGGATCATGATCCCGAACTAACTACGCTACTTTTACTAGATTCTTGGCTCGCTTATGGCTAACCCACTCAGATGTGGCTTACATCATACAATCCCGCCGTAGGTTCACGATGCCGCTGCTGCCTGTGAGCAACCTCGAATGCACCAGGACCTGCTAGGCGGGATATTGTATAGTTGCGACTCTCAACGGTCCTTGACCATTCACGTAGGAATGGCACAGGATTATGCTACCTTTTCGGTGAGGTTTACCAGGTCAGTAACGAGGGTCAGATGTTTGCCTAGAGAGCGCGGTGATGACCATGAGCCATCAAGGTGTTGTCGCGCATTACGTAGCGCTATCCCTAGGCTCGGACTTTCAAGTGCCACTACATCGGGGTTCTTCCGTTTGTATGATAGAAATTCATATCGCCCCGTATAAGTATGATTAAAGACCCTTAAATAGCCATCCCGTGCCACTCCCCGGAAATGTGTCTTCTGTGCACGCTGATTGTGGTTACCGCGATGAATCAAGCAAATTACTAACGATTTGGAACGCTAGACCGAGAGCAGAAGTTAGCCGTTTCCGGTACGAGTACTCCTTGGGTATCTGAACCTGTACTCGCCTATATCACGCCCACAGTAAGTGAAGTTCTCTTTCTCTCCACCTGTCGACTTATCGTGTTG"

# Iteratively change a nucleotide for its corresponding pair (in the DNANucPairs)
myRevC = ''.join([DNANucPairs[nuc] for nuc in myDNA])[::-1]
print(myRevC)

